apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app: homework2-ing
  name: homework2-ing
spec:
  backend:
    serviceName: homework2-srv
    servicePort: 8080
  rules:
    - host: homework2.host
      http:
        paths:
          - path: /
            backend:
              serviceName: homework2-srv
              servicePort: 8080
